# Generated by Django 6.0.4 on 2026-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_actionable_inbox_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_PENDING', 'Booking Pending'), ('SWAP_REQUESTED', 'Swap Requested'), ('SWAP_ACCEPTED', 'Swap Accepted'), ('SWAP_DECLINED', 'Swap Declined'), ('SWAP_EXPIRED', 'Swap Expired'), ('OVERRIDE_GRANTED', 'Override Granted'), ('OVERRIDE_EXPIRING_SOON', 'Override Expiring Soon'), ('OVERRIDE_EXPIRED', 'Override Expired'), ('SYSTEM', 'System'), ('FACULTY_APPROVAL_REQ', 'Faculty Approval Required'), ('FACULTY_APPROVED', 'Faculty Approved'), ('FACULTY_REJECTED', 'Faculty Rejected'), ('FACULTY_ESCALATED', 'Faculty Escalated'), ('FACULTY_RESENT', 'Faculty Resent')], db_index=True, max_length=40),
        ),
    ]
