# Generated by Django 6.0.4 on 2026-06-06 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('domain', models.CharField(max_length=20)),
                ('booking_ref', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve')], default='APPROVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='notificatio_token_h_f3ce36_idx'), models.Index(fields=['booking_ref', 'domain'], name='notificatio_booking_1aef40_idx')],
            },
        ),
    ]
