# Generated by Django 6.0.4 on 2026-05-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_drop_legacy_role_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleoverride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roleoverride',
            name='reason',
            field=models.TextField(help_text='Why this override was granted. Required for audit trail.'),
        ),
        migrations.AlterField(
            model_name='roleoverride',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Leave blank for indefinite. Expires automatically at this time.', null=True),
        ),
    ]
