# Generated by Django 6.0.4 on 2026-05-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0025_alter_spacetimetableblock_date'),
        ('users', '0005_roleoverride_updated_at_alter_roleoverride_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleoverride',
            name='block',
            field=models.ForeignKey(blank=True, help_text='If set, this override applies to this campus block only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_overrides', to='spaces.block'),
        ),
    ]
