# Generated by Django 6.0.4 on 2026-04-29 10:24

import apps.spaces.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension # <-- ADDED IMPORT


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(), # <-- ADDED AS THE ABSOLUTE FIRST OPERATION
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('GENERAL_HALL', 'General Hall'), ('LAB', 'Lab'), ('GUEST_ROOM', 'Guest Room')], max_length=20)),
                ('capacity_hard', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'location'), name='unique_space_location')],
            },
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('remarks_by_admin', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('attendee_count', models.IntegerField()),
                ('purpose_of_booking', models.TextField()),
                ('requested_equipment', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.department')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resolved', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='spaces.space')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [
                    models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), ('remarks_by_admin__isnull', False), _connector='OR'), name='spaces_spacebooking_rejected_requires_remarks'), 
                    models.CheckConstraint(condition=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='space_booking_start_before_end'), 
                    models.CheckConstraint(condition=models.Q(('attendee_count__gt', 0)), name='space_booking_positive_attendees'), 
                    django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'APPROVED')), expressions=[('space', '='), (apps.spaces.models.TsTzRange('start_datetime', 'end_datetime'), '&&')], name='exclude_overlapping_approved_space_bookings')
                ],
            },
        ),
    ]