# Generated by Django 6.0.4 on 2026-05-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('AV', 'Audio/Visual'), ('IT', 'Computers & IT'), ('FURNITURE', 'Furniture'), ('STATIONERY', 'Stationery & Supplies'), ('MEDIA', 'Media Production Gear')], max_length=20)),
                ('total_owned', models.PositiveIntegerField(default=0)),
                ('total_functional', models.PositiveIntegerField(default=0)),
                ('is_returnable', models.BooleanField(default=True, help_text='False for consumables like tape or markers')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spacebooking',
            name='requested_equipment',
        ),
        migrations.AddField(
            model_name='space',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/'),
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaces.equipment')),
                ('space_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_equipment', to='spaces.spacebooking')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('space_booking__isnull', False)), name='equipment_request_must_have_booking')],
            },
        ),
        migrations.CreateModel(
            name='SpaceEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaces.equipment')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_in_equipment', to='spaces.space')),
            ],
            options={
                'verbose_name_plural': 'Space Equipment',
                'constraints': [models.UniqueConstraint(fields=('space', 'equipment'), name='unique_space_equipment')],
            },
        ),
    ]
