# Generated by Django 6.0.4 on 2026-05-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_equipment_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
