# Generated by Django 6.0.4 on 2026-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_spacebooking_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_special_purpose',
            field=models.BooleanField(default=False, help_text="If True, this space is reserved for specific workflows and won't be auto-suggested."),
        ),
        migrations.AlterField(
            model_name='spacebooking',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
