# Generated by Django 6.0.4 on 2026-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_space_is_special_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_standard_media_kit',
            field=models.BooleanField(default=False, help_text='If True, automatically assigns 1 unit to every Media Team request.'),
        ),
    ]
