# Generated by Django 6.0.4 on 2026-05-15 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_space_buffers_and_lab_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebooking',
            name='booking_type',
            field=models.CharField(choices=[('SINGLE', 'Single / Continuous'), ('RECURRING', 'Recurring Daily')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
