# Generated by Django 6.0.4 on 2026-05-19 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_spacebooking_booking_type_spacebooking_group_id'),
        ('users', '0005_roleoverride_updated_at_alter_roleoverride_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='approval_category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LAB', 'Lab'), ('LIBRARY', 'Library')], default='GENERAL', help_text='Determines which role type approves bookings for this space.', max_length=20),
        ),
        migrations.AddField(
            model_name='space',
            name='block',
            field=models.ForeignKey(blank=True, help_text='Campus block this space belongs to. Scopes RECEPTIONIST assignments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='spaces.block'),
        ),
        migrations.CreateModel(
            name='SpaceApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('BLOCK', 'Block'), ('SPACE', 'Space')], help_text='Whether this assignment scopes to a block or a specific space.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, help_text='Set when scope_type=BLOCK.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver_assignments', to='spaces.block')),
                ('role', models.ForeignKey(help_text='Must be RECEPTIONIST, LAB_INCHARGE, or LIBRARIAN.', on_delete=django.db.models.deletion.PROTECT, related_name='space_approver_assignments', to='users.role')),
                ('space', models.ForeignKey(blank=True, help_text='Set when scope_type=SPACE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver_assignments', to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_approver_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('block__isnull', False), ('is_active', True), ('scope_type', 'BLOCK')), fields=('user', 'role', 'block'), name='unique_active_block_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'SPACE'), ('space__isnull', False)), fields=('user', 'role', 'space'), name='unique_active_space_assignment')],
            },
        ),
    ]
