# Generated by Django 6.0.4 on 2026-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_block_space_approval_category_space_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='approval_workflow_type',
            field=models.CharField(choices=[('DIRECT', 'Direct Approver'), ('HOD_FALLBACK', 'HOD with Fallback')], default='DIRECT', help_text='Determines whether approvals are direct or routed through a hierarchical fallback workflow.', max_length=30),
        ),
    ]
