# Generated by Django 6.0.4 on 2026-05-21 15:07

from django.db import migrations


def forwards(apps, schema_editor):
    Space = apps.get_model('spaces', 'Space')
    Space.objects.filter(is_lab=True).update(approval_category='LAB')


def backwards(apps, schema_editor):
    Space = apps.get_model('spaces', 'Space')
    Space.objects.filter(approval_category='LAB').update(is_lab=True)


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_alter_spacebooking_status'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
