# Generated by Django 6.0.4 on 2026-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0013_backfill_is_lab_to_category_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='is_lab',
        ),
    ]
