# Generated by Django 6.0.4 on 2026-05-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0015_spaceavailabilitywindow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpaceAvailabilityWindow',
        ),
    ]
