# Generated by Django 6.0.4 on 2026-05-24 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0018_alter_spacebooking_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebooking',
            name='faculty_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='faculty_sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spacebooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed'), ('AWAITING_FACULTY', 'Awaiting Faculty Approval'), ('FACULTY_ESCALATED', 'Sent to Incharge (Faculty Pending)')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
