# Generated by Django 6.0.4 on 2026-05-24 13:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0019_spacebooking_faculty_response_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceApproverChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_systems', models.PositiveIntegerField(blank=True, help_text='Total bookable units. Leave blank for no limit.', null=True)),
                ('escalation_hours', models.PositiveIntegerField(default=24, help_text='Hours before booking escalates to fallback approver.')),
                ('requires_reason', models.BooleanField(default=True, help_text='If true, booking purpose is mandatory.')),
                ('earliest_start', models.TimeField(blank=True, help_text='Earliest allowed booking start time. Leave blank for no restriction.', null=True)),
                ('latest_end', models.TimeField(blank=True, help_text='Latest allowed booking end time. Leave blank for no restriction.', null=True)),
                ('fallback_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallback_chains', to=settings.AUTH_USER_MODEL)),
                ('primary_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_chains', to=settings.AUTH_USER_MODEL)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approver_chain', to='spaces.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceCategoryAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_category', models.CharField(max_length=50)),
                ('allowed_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_category',), name='unique_from_category_affinity')],
            },
        ),
        migrations.CreateModel(
            name='SpaceSystemBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systems_allocated', models.PositiveIntegerField(default=0)),
                ('space_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_booking', to='spaces.spacebooking')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_label', models.CharField(default='', max_length=200)),
                ('row_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_batches', to='spaces.space')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceTimetableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(default='', max_length=200)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_blocks', to='spaces.space')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='spaces.timetableuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['space', 'date', 'start_time', 'end_time'], name='spaces_spac_space_i_eb098b_idx')],
            },
        ),
    ]
