# Generated by Django 6.0.4 on 2026-05-24 13:01

from django.db import migrations

def seed_space_category_affinities(apps, schema_editor):
    SpaceCategoryAffinity = apps.get_model('spaces', 'SpaceCategoryAffinity')
    affinities = [
        ('LAB', ['LAB']),
        ('GENERAL_HALL', ['GENERAL_HALL']),
        ('GUEST_ROOM', ['GUEST_ROOM']),
    ]
    for from_cat, allowed in affinities:
        SpaceCategoryAffinity.objects.get_or_create(
            from_category=from_cat,
            defaults={'allowed_categories': allowed}
        )

def reverse_seed(apps, schema_editor):
    pass  # safe to leave rows on rollback

class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0020_spaceapproverchain_spacecategoryaffinity_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_space_category_affinities, reverse_seed),
    ]
