# Generated by Django 6.0.4 on 2026-05-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0021_seed_space_category_affinity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceapproverchain',
            name='total_systems',
        ),
    ]
