# Generated by Django 6.0.4 on 2026-05-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0022_remove_spaceapproverchain_total_systems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpaceSystemBooking',
        ),
    ]
