# Generated by Django 6.0.4 on 2026-05-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0023_delete_spacesystembooking"),
        ("users", "0005_roleoverride_updated_at_alter_roleoverride_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Assigned department for HOD-routed approval workflows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='users.department'),
        ),
    ]
