# Generated by Django 6.0.4 on 2026-05-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0024_space_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacetimetableblock',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
