# Generated by Django 6.0.4 on 2026-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0025_alter_spacetimetableblock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebooking',
            name='faculty_timed_out',
            field=models.BooleanField(default=False, help_text='True when this booking escalated because faculty did not respond within the deadline. False when faculty manually approved it.'),
        ),
    ]
