# Generated by Django 6.0.4 on 2026-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0027_seed_general_hall_lab_affinity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacebooking',
            name='faculty_timed_out',
            field=models.BooleanField(default=False, help_text='Indicates that approval was escalated after faculty non-response.'),
        ),
    ]
