# Generated by Django 6.0.4 on 2026-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0029_spacebooking_chain_escalated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('GENERAL_HALL', 'General Hall'), ('LAB', 'Lab'), ('GUEST_ROOM', 'Guest Room'), ('CLASSROOM', 'Classroom')], max_length=20),
        ),
    ]
