# Generated by Django 6.0.4 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0030_add_classroom_space_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacetimetableblock",
            name="instructor",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
