# Generated by Django 6.0.4 on 2026-09-05 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0031_spacetimetableblock_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacetimetableblock',
            name='instructor_user',
            field=models.ForeignKey(blank=True, help_text='Resolved CustomUser match for the instructor field, if any. Null means unmatched — the raw instructor string is the source of truth for display in that case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_timetable_blocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
