# Generated by Django 6.0.4 on 2026-05-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('TRANSPORT', 'Transport'), ('MEDIA', 'Media'), ('MESS', 'Mess')], max_length=20, unique=True)),
                ('require_hod_approval', models.BooleanField(default=True)),
            ],
        ),
    ]
