# Generated by Django 6.0.4 on 2026-05-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleApprovalConfig',
        ),
    ]
