# Generated by Django 6.0.4 on 2026-05-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_fleetbooking_status'),
        ('users', '0005_roleoverride_updated_at_alter_roleoverride_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetbooking',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.department'),
        ),
    ]
