# Generated by Django 6.0.4 on 2026-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_fleetbooking_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed'), ('AWAITING_FACULTY', 'Awaiting Faculty Approval'), ('FACULTY_ESCALATED', 'Sent to Incharge (Faculty Pending)')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
