# Generated by Django 6.0.4 on 2026-05-16 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0009_spacebooking_booking_type_spacebooking_group_id'),
        ('users', '0003_alter_customuser_designation_delete_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_events', models.PositiveIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Settings',
                'verbose_name_plural': 'Media Settings',
            },
        ),
        migrations.CreateModel(
            name='MediaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('remarks_by_admin', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=200)),
                ('setup_start_datetime', models.DateTimeField(db_index=True)),
                ('event_start_datetime', models.DateTimeField()),
                ('event_end_datetime', models.DateTimeField()),
                ('teardown_end_datetime', models.DateTimeField(db_index=True)),
                ('requested_services', models.TextField(blank=True, null=True)),
                ('is_external_event', models.BooleanField(default=False, help_text='True if this event is organised by an external party outside the college.')),
                ('is_team_request', models.BooleanField(default=False, help_text='True when the requester needs the media team to cover the event.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.department')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resolved', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_bookings', to='spaces.space')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaEquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaces.equipment')),
                ('media_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='media.mediabooking')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), ('remarks_by_admin__isnull', False), _connector='OR'), name='media_mediabooking_rejected_requires_remarks'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('setup_start_datetime__lte', models.F('event_start_datetime'))), name='media_setup_before_event_start'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('event_start_datetime__lt', models.F('event_end_datetime'))), name='media_event_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('event_end_datetime__lte', models.F('teardown_end_datetime'))), name='media_event_end_before_teardown'),
        ),
        migrations.AddConstraint(
            model_name='mediaequipmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='media_equipment_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='mediaequipmentrequest',
            constraint=models.UniqueConstraint(fields=('media_booking', 'equipment'), name='unique_equipment_per_media_booking'),
        ),
    ]
