# Generated by Django 6.0.4 on 2026-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabooking',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
