# Generated by Django 6.0.4 on 2026-05-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediabooking_organization'),
        ('spaces', '0006_space_is_special_purpose_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaEquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mediabooking',
            name='media_booking_start_before_end',
        ),
        migrations.RenameField(
            model_name='mediabooking',
            old_name='end_time',
            new_name='event_end_time',
        ),
        migrations.RenameField(
            model_name='mediabooking',
            old_name='start_time',
            new_name='event_start_time',
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='setup_start_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='teardown_end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('setup_start_time__lte', models.F('event_start_time'))), name='media_setup_before_event_start'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('event_start_time__lt', models.F('event_end_time'))), name='media_event_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('event_end_time__lte', models.F('teardown_end_time'))), name='media_event_end_before_teardown'),
        ),
        migrations.AddField(
            model_name='mediaequipmentrequest',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaces.equipment'),
        ),
        migrations.AddField(
            model_name='mediaequipmentrequest',
            name='media_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='media.mediabooking'),
        ),
        migrations.RemoveField(
            model_name='mediabooking',
            name='requested_equipment',
        ),
        migrations.AddConstraint(
            model_name='mediaequipmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='media_equipment_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='mediaequipmentrequest',
            constraint=models.UniqueConstraint(fields=('media_booking', 'equipment'), name='unique_equipment_per_media_booking'),
        ),
    ]
