# Generated by Django 6.0.4 on 2026-05-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediaequipmentrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediabooking',
            name='technical_contact_person',
        ),
    ]
