# Generated by Django 6.0.4 on 2026-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_mediabooking_technical_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediabooking',
            name='organization',
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='is_external_event',
            field=models.BooleanField(default=False, help_text='True if this event is organised by an external party outside the college.'),
        ),
    ]
