# Generated by Django 6.0.4 on 2026-05-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_mediabooking_organization_and_more'),
        ('spaces', '0006_space_is_special_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_events', models.PositiveIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Settings',
                'verbose_name_plural': 'Media Settings',
            },
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='is_team_request',
            field=models.BooleanField(default=False, help_text='True when the requester needs the media team to cover the event.'),
        ),
        migrations.CreateModel(
            name='MediaTeamKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spaces.equipment')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='standard_kit_items', to='media.mediasettings')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('settings', 'equipment'), name='unique_media_team_kit_equipment'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='media_team_kit_quantity_positive')],
            },
        ),
    ]
