# Generated by Django 6.0.4 on 2026-05-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_mediasettings_mediabooking_is_team_request_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediateamkititem',
            name='unique_media_team_kit_equipment',
        ),
        migrations.RemoveConstraint(
            model_name='mediateamkititem',
            name='media_team_kit_quantity_positive',
        ),
        migrations.DeleteModel(
            name='MediaTeamKitItem',
        ),
    ]
