# Generated by Django 6.0.4 on 2026-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_remove_mediateamkititem_unique_media_team_kit_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediabooking',
            name='media_setup_before_event_start',
        ),
        migrations.RemoveConstraint(
            model_name='mediabooking',
            name='media_event_start_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='mediabooking',
            name='media_event_end_before_teardown',
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='event_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='event_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='setup_start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='teardown_end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
