# Generated by Django 6.0.4 on 2026-05-14 13:57

import datetime
from django.db import migrations
from django.utils import timezone

def combine_dates_and_times(apps, schema_editor):
    # We use apps.get_model to get the historical version of the model
    # This ensures the migration runs safely regardless of future model changes
    MediaBooking = apps.get_model('media', 'MediaBooking')
    
    for booking in MediaBooking.objects.all():
        # Combine the old Date and Time into a timezone-aware DateTime
        if booking.booking_date:
            if booking.setup_start_time:
                dt = datetime.datetime.combine(booking.booking_date, booking.setup_start_time)
                booking.setup_start_datetime = timezone.make_aware(dt)
                
            if booking.event_start_time:
                dt = datetime.datetime.combine(booking.booking_date, booking.event_start_time)
                booking.event_start_datetime = timezone.make_aware(dt)
                
            if booking.event_end_time:
                dt = datetime.datetime.combine(booking.booking_date, booking.event_end_time)
                booking.event_end_datetime = timezone.make_aware(dt)
                
            if booking.teardown_end_time:
                dt = datetime.datetime.combine(booking.booking_date, booking.teardown_end_time)
                booking.teardown_end_datetime = timezone.make_aware(dt)
                
            # Save the updated datetime fields back to the database
            booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_remove_mediabooking_media_setup_before_event_start_and_more'),
    ]

    operations = [
        # Run the Python script, and do nothing if this migration is reversed
        migrations.RunPython(combine_dates_and_times, reverse_code=migrations.RunPython.noop),
    ]