# Generated by Django 6.0.4 on 2026-05-14 14:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20260514_1927'),
        ('spaces', '0007_equipment_is_standard_media_kit'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediabooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='mediabooking',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='mediabooking',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='mediabooking',
            name='setup_start_time',
        ),
        migrations.RemoveField(
            model_name='mediabooking',
            name='teardown_end_time',
        ),
        migrations.AlterField(
            model_name='mediabooking',
            name='event_end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 14, 3, 13, 917677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediabooking',
            name='event_start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 14, 3, 17, 769434, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediabooking',
            name='setup_start_datetime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 14, 14, 3, 20, 882040, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediabooking',
            name='teardown_end_datetime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 14, 14, 3, 24, 796175, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('setup_start_datetime__lte', models.F('event_start_datetime'))), name='media_setup_before_event_start'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('event_start_datetime__lt', models.F('event_end_datetime'))), name='media_event_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='mediabooking',
            constraint=models.CheckConstraint(condition=models.Q(('event_end_datetime__lte', models.F('teardown_end_datetime'))), name='media_event_end_before_teardown'),
        ),
    ]
