# Generated by Django 6.0.4 on 2026-05-26 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_alter_mediabooking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasettings',
            name='max_concurrent_events',
        ),
        migrations.AddField(
            model_name='mediabooking',
            name='assigned_crew',
            field=models.ManyToManyField(blank=True, help_text='Media team members assigned to cover this booking. Set at approval time.', related_name='assigned_media_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
