# Generated by Django 6.0.4 on 2026-05-01 17:19

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('remarks_by_admin', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(db_index=True)),
                ('delivery_time', models.TimeField()),
                ('delivery_location', models.CharField(max_length=255)),
                ('purpose_of_programme', models.TextField()),
                ('total_persons', models.IntegerField()),
                ('veg_persons', models.IntegerField(default=0)),
                ('nonveg_persons', models.IntegerField(default=0)),
                ('breakfast_required', models.BooleanField(default=False)),
                ('breakfast_menu', models.TextField(blank=True, null=True)),
                ('morning_tea_required', models.BooleanField(default=False)),
                ('morning_snack_option', models.CharField(blank=True, max_length=50, null=True)),
                ('lunch_required', models.BooleanField(default=False)),
                ('lunch_menu', models.TextField(blank=True, null=True)),
                ('evening_tea_required', models.BooleanField(default=False)),
                ('evening_snack_option', models.CharField(blank=True, max_length=50, null=True)),
                ('dinner_required', models.BooleanField(default=False)),
                ('dinner_menu', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.department')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resolved', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), ('remarks_by_admin__isnull', False), _connector='OR'), name='mess_messbooking_rejected_requires_remarks'), models.CheckConstraint(condition=models.Q(('total_persons__gt', 0)), name='mess_booking_positive_total_persons'), models.CheckConstraint(condition=models.Q(('total_persons', django.db.models.expressions.CombinedExpression(models.F('veg_persons'), '+', models.F('nonveg_persons')))), name='mess_booking_headcount_math_check'), models.CheckConstraint(condition=models.Q(('veg_persons__gte', 0), ('nonveg_persons__gte', 0)), name='mess_booking_no_negative_meals')],
            },
        ),
    ]
