# Generated by Django 6.0.4 on 2026-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messbooking',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='messbooking',
            name='breakfast_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messbooking',
            name='dinner_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messbooking',
            name='evening_tea_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messbooking',
            name='lunch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messbooking',
            name='morning_tea_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
