# Generated by Django 6.0.4 on 2026-05-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_remove_messbooking_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messbooking',
            name='rejection_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
