# Generated by Django 6.0.4 on 2026-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0007_remove_migrated_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
